require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.nvim-cmp"
require "user.lsp"

-- Plugin config
require "user.autopairs"
require "user.treesitter"
require "user.comment"
require "user.impatient"
require "user.nvim-tree"
require "user.gitsigns"
require "user.surround"
require "user.telescope"
require "user.toggleterm"
require "user.alpha"
require "user.project"
require "user.lualine"
require "user.neotest"
require "user.other"
