require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.nvim-cmp"
require "user.lsp"

-- Plugin config
require "user.comment"
require "user.impatient"
require "user.nvim-tree"
require "user.nvim-treesitter"
require "user.gitsigns"
require "user.surround"
require "user.telescope"
require "user.jester"
